USE DWSUCOS;
SELECT A.COD_ORGANIZACIONAL AS COD_VENDEDOR, A.DESC_ORGANIZACIONAL AS DESC_VENDEDOR,
B.COD_ORGANIZACIONAL AS COD_GERENTE, B.DESC_ORGANIZACIONAL AS DESC_GERENTE,
C.COD_ORGANIZACIONAL AS COD_DIRETOR, C.DESC_ORGANIZACIONAL AS DESC_DIRETOR
FROM DIM_ORGANIZACIONAL A 
INNER JOIN DIM_ORGANIZACIONAL B ON A.cod_organizacional_superior = B.COD_ORGANIZACIONAL
INNER JOIN DIM_ORGANIZACIONAL C ON B.cod_organizacional_superior = C.COD_ORGANIZACIONAL
WHERE A.DIREITA - A.ESQUERDA = 1
UNION
SELECT A.COD_ORGANIZACIONAL AS COD_VENDEDOR, A.DESC_ORGANIZACIONAL AS DESC_VENDEDOR,
B.COD_ORGANIZACIONAL AS COD_GERENTE, B.DESC_ORGANIZACIONAL AS DESC_GERENTE,
B.COD_ORGANIZACIONAL AS COD_DIRETOR, B.DESC_ORGANIZACIONAL AS DESC_DIRETOR
FROM DIM_ORGANIZACIONAL A 
INNER JOIN DIM_ORGANIZACIONAL B ON A.cod_organizacional_superior = B.COD_ORGANIZACIONAL
WHERE A.DIREITA - A.ESQUERDA = 1 AND B.cod_organizacional_superior = ''