USE DWSUCOS;
SELECT DIM_CATEGORIA.COD_CATEGORIA, DIM_CATEGORIA.DESC_CATEGORIA,
DIM_MARC.COD_MARCA, DIM_MARC.DESC_MARCA,
DIM_PRODUTO .COD_PRODUTO, DIM_PRODUTO.DESC_PRODUTO, DIM_PRODUTO.ATR_SABOR, 
DIM_PRODUTO.ATR_TAMANHO FROM
DIM_PRODUTO
INNER JOIN DIM_MARC ON DIM_PRODUTO.COD_MARCA = DIM_MARC.COD_MARCA
INNER JOIN DIM_CATEGORIA ON DIM_MARC.COD_CATEGORIA = DIM_CATEGORIA.COD_CATEGORIA;